src/main/java/com/swmStrong/demo/config/cors/WebConfig.java

---
---
---
예시:
- query 및 mutation 기능을 연결하였습니다.
- 리팩토링을 통해 Service → Facade 레이어로 추상화하였습니다.
- 기존 메서드의 네이밍을 변경하고 테스트 코드를 추가하였습니다.
---
---
---
---

fix: http 환경-자격증명 비허용으로 변경

---

src/main/java/com/swmStrong/demo/domain/categoryPattern/entity/CategoryPattern.java
src/main/java/com/swmStrong/demo/domain/leaderboard/consumer/LeaderboardStreamConsumer.java
src/main/java/com/swmStrong/demo/domain/leaderboard/controller/LeaderboardController.java
src/main/java/com/swmStrong/demo/domain/leaderboard/repository/LeaderboardRepository.java
src/main/java/com/swmStrong/demo/domain/leaderboard/repository/LeaderboardRepositoryImpl.java
src/main/java/com/swmStrong/demo/domain/leaderboard/service/LeaderboardService.java
src/main/java/com/swmStrong/demo/domain/leaderboard/service/LeaderboardServiceImpl.java

---
---
리더보드를 날짜별로 관리하는 기능을 추가
---
현재 리더보드가 날짜 단위로 구분되어있지 않아 날짜 단위의 키를 추가하고,
추가적으로 페이징 기능을 넣어두었습니다.
---
약 5분 정도 예상됩니다.
---
---
---
#12 리더보드 날짜별 관리

[SWM-69] 리더보드 날짜별 관리

---

src/main/java/com/swmStrong/demo/domain/user/controller/UserController.java
src/main/java/com/swmStrong/demo/domain/user/entity/User.java
src/main/java/com/swmStrong/demo/domain/user/repository/UserRepository.java
src/main/java/com/swmStrong/demo/domain/user/service/UserService.java
src/main/java/com/swmStrong/demo/domain/user/service/UserServiceImpl.java

---
---
기존에 말했던 user 엔티티에서 deviceId 칼럼 제거
database 정책 update로 변경
controller에 operation 설명 추가
---
예시:
- query 및 mutation 기능을 연결하였습니다.
- 리팩토링을 통해 Service → Facade 레이어로 추상화하였습니다.
- 기존 메서드의 네이밍을 변경하고 테스트 코드를 추가하였습니다.
---
1~2분 예상합니다.
---
---
---

[CHORE] 유저 entity 수정 및 api 문서 구체화

---

src/main/java/com/swmStrong/demo/domain/categoryPattern/dto/CategoryPatternJSONDto.java
src/main/java/com/swmStrong/demo/domain/categoryPattern/dto/CategoryRequestDto.java
src/main/java/com/swmStrong/demo/domain/categoryPattern/dto/PatternRequestDto.java
src/main/java/com/swmStrong/demo/domain/categoryPattern/initializer/CategoryPatternInitializer.java
src/main/java/com/swmStrong/demo/domain/categoryPattern/service/CategoryPatternService.java
src/main/java/com/swmStrong/demo/domain/categoryPattern/service/CategoryPatternServiceImpl.java
src/main/java/com/swmStrong/demo/domain/matcher/core/PatternMatcher.java
src/main/java/com/swmStrong/demo/domain/usageLog/entity/UsageLog.java
src/main/java/com/swmStrong/demo/domain/usageLog/service/UsageLogServiceImpl.java
src/main/java/com/swmStrong/demo/infra/json/JsonLoader.java
src/main/resources/data/category-patterns.json

---
---
---
json loader를 위해 공통 컴포넌트를 만들었습니다.
json에 카테고리-색깔-패턴을 매칭해두고, 쉽게 수정할 수 있도록 분리해두었습니다.
patternMatcher의 자잘한 버그를 수정했습니다.
usageLog에서 미분류 카테고리의 저장방식을 수정했습니다. 
---
약 10분 정도 예상됩니다.
---
---
---
#14 초기 카테고리-패턴 설정

[SWM-71] 초기 카테고리-패턴 설정

---

src/main/java/com/swmStrong/demo/domain/categoryPattern/controller/CategoryPatternController.java
src/main/java/com/swmStrong/demo/domain/categoryPattern/dto/CategoryPatternJSONDto.java
src/main/java/com/swmStrong/demo/domain/categoryPattern/dto/CategoryRequestDto.java
src/main/java/com/swmStrong/demo/domain/categoryPattern/entity/CategoryPattern.java
src/main/java/com/swmStrong/demo/domain/categoryPattern/facade/CategoryProviderImpl.java
src/main/java/com/swmStrong/demo/domain/categoryPattern/initializer/CategoryPatternInitializer.java
src/main/java/com/swmStrong/demo/domain/categoryPattern/service/CategoryPatternService.java
src/main/java/com/swmStrong/demo/domain/categoryPattern/service/CategoryPatternServiceImpl.java
src/main/java/com/swmStrong/demo/domain/leaderboard/service/LeaderboardServiceImpl.java
src/main/resources/data/category-patterns.json

---
---
categoryPattern 정렬 우선순위 설정
---
categoryPattern entity에 priority를 추가해 우선순위를 나타내게 했습니다. 
---
약 5분 정도 예상됩니다.
---
---
---
#31 categoryPattern 정렬 순서

[SWM-83] categoryPattern 정렬 우선순위 설정

---

src/main/java/com/swmStrong/demo/config/EncryptorConfig.java
src/main/java/com/swmStrong/demo/domain/userPaymentMethod/converter/BillingKeyCryptoConverter.java
src/main/java/com/swmStrong/demo/domain/userSubscription/controller/UserSubscriptionController.java

---
---
- securityprincipal 관련 수정
- encryptor bean 등록
---
- encryptor가 추가 설정이 필요하기에 bean 으로 따로 분리해 관리합니다.
- securityprincipal record로 바꾼 사이드이펙트를 개선합니다.
---
약 5분 정도 예상됩니다.
---
---
---
#46

[SWM-97] encryptor, securityprincipal 관련 문제 수정

---

src/main/java/com/swmStrong/demo/config/security/WhiteListConfig.java
src/main/java/com/swmStrong/demo/domain/leaderboard/controller/LeaderboardController.java
src/main/java/com/swmStrong/demo/domain/leaderboard/service/LeaderboardService.java
src/main/java/com/swmStrong/demo/domain/leaderboard/service/LeaderboardServiceImpl.java
src/main/java/com/swmStrong/demo/domain/usageLog/controller/UsageLogController.java
src/main/java/com/swmStrong/demo/domain/usageLog/dto/CategoryHourlyUsageDto.java
src/main/java/com/swmStrong/demo/domain/usageLog/repository/UsageLogRepository.java
src/main/java/com/swmStrong/demo/domain/usageLog/service/UsageLogService.java
src/main/java/com/swmStrong/demo/domain/usageLog/service/UsageLogServiceImpl.java
src/main/java/com/swmStrong/demo/domain/user/controller/UserController.java
src/main/java/com/swmStrong/demo/domain/user/dto/NicknameRequestDto.java
src/main/java/com/swmStrong/demo/domain/user/entity/User.java
src/main/java/com/swmStrong/demo/domain/user/service/UserService.java
src/main/java/com/swmStrong/demo/domain/user/service/UserServiceImpl.java

---
---
- 단위 시간별 유저 사용 로그 조회
---
- MongoDB의 Aggregation을 통해 데이터를 시간단위로 구분하여 집계합니다.
---
- 약 3분 정도 예상됩니다.
---
---
---
#58 시간대별 사용 로그 반환

[SWM-103] 단위 시간별 유저 사용 로그 조회

---

src/main/java/com/swmStrong/demo/domain/matcher/core/PatternClassifier.java
src/main/java/com/swmStrong/demo/infra/LLM/GeminiClassifier.java

---
---
- 프롬프트 개선
- 패턴 미분류 시 uncategorized로 반환
---
- 프롬프트 내용을 일부 개선했습니다.
- 패턴 미 분류 시 null로 리턴하여 오류가 발생했는데, 이를 마지막에 Uncategorized로 반환할 수 있게 하여 개선했습니다.
---
- 약 5분 정도 예상됩니다.
---
---
---
#76 프롬프트 개선 및 미분류 시 로직

[SWM-112] 프롬프트 개선 및 미분류 시 로직 추가

---

src/main/java/com/swmStrong/demo/config/security/SecurityConfig.java
src/main/java/com/swmStrong/demo/config/security/filter/TokenAuthorizationFilter.java
src/main/java/com/swmStrong/demo/config/security/handler/CustomAuthenticationEntryPoint.java
src/main/java/com/swmStrong/demo/infra/token/TokenManager.java

---
---
- Security 내 Exception Handling 구조 개선
---
- Exception Handling 이 제대로 되지 않고 있던 문제를 해결했습니다.
- EntryPoint로 ExceptionHandling 을 관리하고, error 전체를 throw 하는 것이 아니라 필요한 부분만 log로 표시하도록 변경했습니다.
---
- 약 5분 정도 예상됩니다.
---
---
---

[Refactor] 토큰 관련 에러 핸들링 변경

---

src/main/java/com/swmStrong/demo/common/exception/code/ErrorCode.java
src/main/java/com/swmStrong/demo/domain/categoryPattern/dto/CategoryPatternJSONDto.java
src/main/java/com/swmStrong/demo/domain/usageLog/dto/CategoryHourlyUsageDto.java
src/main/java/com/swmStrong/demo/domain/usageLog/dto/CategoryUsageDto.java
src/main/java/com/swmStrong/demo/domain/usageLog/repository/UsageLogRepository.java
src/main/java/com/swmStrong/demo/domain/usageLog/service/UsageLogServiceImpl.java

---
---
- usageLog N+1 쿼리 문제 해결
- category color 삭제 이후 사이드이펙트 정리
---
- usageLog가 각 라인마다 save 메서드를 호출하는 것에서 saveAll을 호출하는 것으로 변경했습니다.
- category color 를 삭제한 이후 미처 삭제하지 않았던 부분을 체크해서 삭제했습니다.
---
- 약 5분 정도 예상됩니다.
---
---
---

[Refactor] 사용 로그 관련 리팩토링

---

src/main/java/com/swmStrong/demo/domain/matcher/core/Trie.java

---
---
- 대소문자 구분 해제 
---
- 패턴 비교에서 소문자로만 패턴을 작성했었는데, 소문자로만 구분하는 로직을 추가했습니다.
---
---
---
---
#81 패턴 비교 시 대소문자를 구분하는 문제

fix: 대소문자를 구분하고 있는 문제 해결

---

src/main/java/com/swmStrong/demo/DemoApplication.java
src/main/java/com/swmStrong/demo/common/exception/GlobalExceptionHandler.java
src/main/java/com/swmStrong/demo/common/exception/code/ErrorCode.java
src/main/java/com/swmStrong/demo/config/security/handler/CustomAuthenticationEntryPoint.java
src/main/java/com/swmStrong/demo/domain/common/util/TimeZoneUtil.java
src/main/java/com/swmStrong/demo/domain/leaderboard/service/LeaderboardService.java
src/main/java/com/swmStrong/demo/domain/leaderboard/service/LeaderboardServiceImpl.java
src/main/java/com/swmStrong/demo/domain/usageLog/dto/SaveUsageLogDto.java
src/main/java/com/swmStrong/demo/domain/usageLog/dto/UsageLogResponseDto.java
src/main/java/com/swmStrong/demo/domain/usageLog/entity/UsageLog.java
src/main/java/com/swmStrong/demo/domain/usageLog/repository/UsageLogRepository.java
src/main/java/com/swmStrong/demo/domain/usageLog/service/UsageLogServiceImpl.java
src/main/java/com/swmStrong/demo/message/dto/LeaderBoardUsageMessage.java

---
---
- 시간 관련 변경 작업
- validation 관련 반환값 수정
---
- LocalDateTime을 사용하면서 시간 관련하여 공통된 환경이 필요하다는 판단 하에, 계산의 편의성을 위해 unix timestamp로 변경했습니다.
- jackson이 뱉은 오류를 Spring Security 선에서 오류를 캐치해 401 에러를 반환하는 문제를 수정했습니다.
---
- 약 10분 정도 예상됩니다.
---
---
---
#85 timestamp 타입 변경 
#84 validation error 시 401을 반환하는 문제 
#83 timezone 설정

[SWM-115, SWM-116, SW-117] 시간 관련 변경

---

src/main/java/com/swmStrong/demo/common/exception/code/ErrorCode.java
src/main/java/com/swmStrong/demo/domain/loginCredential/controller/LoginCredentialController.java
src/main/java/com/swmStrong/demo/domain/loginCredential/service/LoginCredentialService.java
src/main/java/com/swmStrong/demo/domain/loginCredential/service/LoginCredentialServiceImpl.java
src/main/java/com/swmStrong/demo/domain/usageLog/service/UsageLogServiceImpl.java
src/main/java/com/swmStrong/demo/domain/user/facade/UserUpdateProvider.java
src/main/java/com/swmStrong/demo/domain/user/facade/UserUpdateProviderImpl.java

---
---
- 간단한 코드 리팩토링
---
- 컨벤션 유지를 위해 띄어쓰기 2개로 되어있는 부분을 수정했습니다.
- 비회원 -> 회원 전환 시 로그인과 동일하게 token을 반환하도록 수정했습니다.
- 시간 검증 시 허용 오차를 두어 client - server 간 발생할 수 있는 오차에 대해 느슨하게 검증할 수 있도록 했습니다.
---
---
---
---

[Refactor] Chores

---

build.gradle
src/main/java/com/swmStrong/demo/config/EmailConfig.java
src/main/java/com/swmStrong/demo/domain/loginCredential/service/LoginCredentialServiceImpl.java
src/main/java/com/swmStrong/demo/infra/mail/EmailTemplate.java
src/main/java/com/swmStrong/demo/infra/mail/EmailTemplateLoader.java
src/main/java/com/swmStrong/demo/infra/mail/MailSender.java
src/main/java/com/swmStrong/demo/infra/mail/dto/SendMailDto.java
src/main/resources/templates/email-verification-template.html
src/main/resources/templates/password-reset-template.html
src/main/resources/templates/welcome-template.html

---
---
- 회원 가입 시 확인 이메일 전송
---
- 회원 가입 시 확인 이메일 전송을 위해 aws ses 세팅과 함께 메일 서비스를 구현했습니다. 
---
---
---
---

[SWM-130] 회원 가입 시 확인 이메일 전송 

---

src/main/java/com/swmStrong/demo/config/security/WhiteListConfig.java
src/main/java/com/swmStrong/demo/domain/categoryPattern/facade/CategoryProvider.java
src/main/java/com/swmStrong/demo/domain/categoryPattern/facade/CategoryProviderImpl.java
src/main/java/com/swmStrong/demo/domain/common/util/TimeZoneUtil.java
src/main/java/com/swmStrong/demo/domain/usageLog/controller/UsageLogController.java
src/main/java/com/swmStrong/demo/domain/usageLog/dto/CategorizedUsageLogDto.java
src/main/java/com/swmStrong/demo/domain/usageLog/dto/MergedCategoryUsageLogDto.java
src/main/java/com/swmStrong/demo/domain/usageLog/service/UsageLogService.java
src/main/java/com/swmStrong/demo/domain/usageLog/service/UsageLogServiceImpl.java

---
---
- 뷰 시각화용 API 메서드
---
- 타임테이블 조회의 경우 스위핑 로직을 구현하려 했으나, 마우스 호버 시 상세정보를 위해 병합하지 않았습니다.
- 최근 로그 조회의 경우 현재는 전체를 반환합니다. 필요 시 pagination을 고려할 수 있습니다. 
---
---
---
---
#92 API for activity list view

[SWM-140] API for activity list view

---

src/main/java/com/swmStrong/demo/domain/usageLog/controller/UsageLogController.java
src/main/java/com/swmStrong/demo/domain/usageLog/dto/MergedCategoryUsageLogDto.java
src/main/java/com/swmStrong/demo/domain/usageLog/repository/UsageLogRepository.java
src/main/java/com/swmStrong/demo/domain/usageLog/service/UsageLogService.java
src/main/java/com/swmStrong/demo/domain/usageLog/service/UsageLogServiceImpl.java

---
---
- 하루 단위로 최근 로그, 타임 라인 반환
---
- startTime, endTime 보다 startedAt, endedAt 이 코드 통일성을 가진다고 판단하여 변경했습니다.
- view 에서 하루 단위로 데이터를 처리하고 있어 최근 로그와 타임라인도 하루 단위로 반환하도록 수정했습니다.
- 일부 swagger 주석 변경을 포함합니다.
---
---
---
---

[SWM-157] 하루 단위로 최근 로그, 타임 라인 반환

---

src/main/java/com/swmStrong/demo/domain/usageLog/service/UsageLogServiceImpl.java

---
---
- 카테고리 stream 처리 중 null로 표시되는 경우 예외처리
---
- 카테고리 stream 처리 중 null로 표시되는 에러가 발생했습니다.
- 예외처리를 통해 null인 경우 Uncategorized로 표시해 NPE를 방지했습니다. 
---
---
---
---

refactor: 카테고리 stream 처리 중 null로 표시되는 경우 예외처리

---

src/main/java/com/swmStrong/demo/config/redis/RedisConfig.java
src/main/java/com/swmStrong/demo/infra/redis/stream/AbstractRedisStreamConsumer.java

---
---
- graceful shutdown
---
- 서버 종료 이전 postDestory 를 설정해 redis connection을 안전하게 제거합니다. 
---
---
---
---

[SWM-158] graceful shutdown

---

src/main/java/com/swmStrong/demo/domain/usageLog/service/UsageLogServiceImpl.java

---
---
- 타임라인 뷰 관련 에러 핸들링
---
- 스위핑 로직 중 예외 사항이 발생하여 로직을 일부 수정했습니다.
- NPE 가 발생하는 원인이 데이터 스트림 처리 중 아직 카테고리가 지정 되지 않은 상태에서 조회하는 경우 발생함을 인지하고 null 에 대한 예외처리를 추가함으로써 해결했습니다.
---
---
---
---
#102 타임라인 뷰 관련 에러 핸들링

[SMW-171] timeline 관련 메서드 로직 변경

---

src/main/java/com/swmStrong/demo/infra/LLM/AbstractLLMClassifier.java
src/main/java/com/swmStrong/demo/infra/LLM/ChatGPTClassifier.java
src/main/java/com/swmStrong/demo/infra/LLM/GeminiClassifier.java
src/main/java/com/swmStrong/demo/infra/LLM/GeminiConfig.java
src/main/java/com/swmStrong/demo/infra/LLM/OpenAIConfig.java
src/main/java/com/swmStrong/demo/infra/LLM/PromptTemplate.java

---
---
- 분류기 기능 추상화
---
- OpenAI(ChatGPT) 와 Gemini의 공통 코드를 추상 클래스로 결합해 상속받아 사용하는 구조로 변경했습니다.
- 프롬프트를 단독 컴포넌트로 만들어 독립적으로 관리할 수 있도록 변경했습니다. 
---
---
---
---

[SWM-186] 분류기 기능 추상화

---

src/main/java/com/swmStrong/demo/domain/streak/controller/StreakController.java
src/main/java/com/swmStrong/demo/domain/streak/service/StreakService.java
src/main/java/com/swmStrong/demo/domain/streak/service/StreakServiceImpl.java
src/main/java/com/swmStrong/demo/infra/LLM/PromptTemplate.java

---
---
- 격자형 스트릭 API 추가
- 세션 요약 프롬프트 수정
---
- 격자형 스트릭 요구사항에 맞춰, 이전의 캘린더형 스트릭 API 에서 매개변수를 변경하여 구현했습니다.
- 메인화면에 짧은 글자수의 요구사항에 맞춰, 컴포넌트를 수정해 30자 이내의 답변을 받을 수 있게 수정했습니다. 
---
---
---
---

[SWM-353] 격자형 스트릭

---

src/main/java/com/swmStrong/demo/domain/pomodoro/dto/AppUsageDto.java
src/main/java/com/swmStrong/demo/domain/pomodoro/dto/CategoryUsageDto.java
src/main/java/com/swmStrong/demo/domain/pomodoro/service/PomodoroServiceImpl.java
src/main/java/com/swmStrong/demo/domain/sessionScore/service/SessionScoreServiceImpl.java

---
---
- 점수 체계 변경
- 주간 통계에 카테고리 별 사용량 추가
---
- 점수 체계를 기존의 가중치를 더하는 방법에서, (일한 시간 / 총 시간)으로 간소화했습니다.
- 클라이언트 요구사항에 따라 주간 통계에 카테고리 별 사용량을 추가했습니다. 
---
---
---
---

[SWM-362] 점수체계 정리

---

src/main/java/com/swmStrong/demo/domain/pomodoro/service/PomodoroServiceImpl.java
src/main/java/com/swmStrong/demo/domain/sessionScore/dto/SessionDashboardDto.java
src/main/java/com/swmStrong/demo/domain/sessionScore/dto/SessionScoreResponseDto.java
src/main/java/com/swmStrong/demo/domain/sessionScore/entity/SessionScore.java
src/main/java/com/swmStrong/demo/domain/sessionScore/facade/SessionScoreProvider.java
src/main/java/com/swmStrong/demo/domain/sessionScore/service/SessionScoreServiceImpl.java
src/main/java/com/swmStrong/demo/infra/LLM/PromptTemplate.java
src/main/java/com/swmStrong/demo/message/dto/SummaryResult.java

---
---
- summary title 영어 추가
---
- i18n의 일환으로 추가되었습니다.
- 클라이언트에서 한글 - 영어 선택을 할 때, title은 한글로만 반환되어 이를 해결하고자 영어 반환값도 같이 가지게 해 해결했습니다.
- 미리 두 가지의 값을 모두 LLM을 통해 반환하여 실시간 번역으로 인한 불안정성을 제거하고, 안정적으로 사용할 수 있습니다. 
---
---
---
---

[SWM-370] summary title 영어 추가

---

src/main/java/com/swmStrong/demo/common/exception/GlobalExceptionHandler.java
src/main/java/com/swmStrong/demo/config/security/SecurityConfig.java
src/main/java/com/swmStrong/demo/config/security/filter/ExceptionHandlingFilter.java
src/main/java/com/swmStrong/demo/config/security/filter/TokenAuthorizationFilter.java
src/main/java/com/swmStrong/demo/domain/group/dto/GroupContext.java
src/main/java/com/swmStrong/demo/domain/group/service/GroupAuthorizationProvider.java
src/main/java/com/swmStrong/demo/domain/group/service/GroupService.java
src/main/java/com/swmStrong/demo/domain/group/service/GroupServiceImpl.java

---
---
- Group 리팩토링
---
- `GroupServiceImpl.java`의 가독성 향상을 위해 검증 로직을 분리했습니다.
- `@PreAuthorize` 어노테이션의 예외처리가 되고 있지 않은 부분을 수정했습니다.
- Seucirty에서 json 파싱 에러가 인증 에러로 처리되는 현상을 수정했습니다.
- 키 형식을 다른 서비스와 동일한 방식으로 수정했습니다.
---
---
---
---

[SWM-383] Group 리팩토링
